[package]
name = "i3ttd"
version = "0.1.0"
authors = ["Boris Faure <boris@fau.re>"]
license = "BSD-2-Clause"

[dependencies]
debug_macros = "0.0.1"
docopt = "0.7"
i3ipc = "0.4"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
time = "0.1"
